spring.application.name=UserOperationsManagement
# --- Database Configuration ---
spring.datasource.url=jdbc:mysql://localhost:3306/users?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=Vaibhavi@2004
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# --- Hibernate Configuration ---
spring.jpa.hibernate.ddl-auto=update  
# options: none, validate, update, create, create-drop
spring.jpa.show-sql=true             
 # Show SQL in console
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# --- Connection Pool (Optional tuning) ---
spring.datasource.initialization-mode=always
spring.datasource.hikari.maximum-pool-size=10

# --- Logging (Optional) ---
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

spring.application.name=UserOperationsManagement
